# -*- coding: utf-8 -*-
"""COVID-19 Data Analysis & Dashboard System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLSuAF-Yd8MzKDXp8CIliFZmArLkcO8F
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/covid_19_clean_complete.csv")

province_state = df["Province/State"].to_numpy()
print(province_state)

Country_Region = df["Country/Region"].to_numpy()
print(province_state)

Lat = df["Lat"].to_numpy()
print(Lat)

Long = df["Long"].to_numpy()
print(Long)

Date = df["Date"].to_numpy()
print(Date)

Confirmed = df["Confirmed"].to_numpy()
print(Confirmed)

Deaths = df["Deaths"].to_numpy()
print(Deaths)

Recovered = df["Recovered"].to_numpy()
print(Recovered)

Active = df["Active"].to_numpy()
print(Active)

WHO_Region = df["WHO Region"].to_numpy()
print(WHO_Region)

selected_columns = [
    'Province/State',
    'Country/Region',
    'Lat',
    'Long',
    'Date',
    'Confirmed',
    'Deaths',
    'Recovered',
    'Active',
    'WHO Region'
]

df_selected = df[selected_columns].copy()
display(df_selected.head())

missing_values = df_selected.isnull().sum()
display(missing_values[missing_values > 0])

df_selected['Province/State'] = df_selected['Province/State'].fillna('Unknown')
missing_values = df_selected.isnull().sum()
display(missing_values[missing_values > 0])

df_selected['Date'] = pd.to_datetime(df_selected['Date'])
display(df_selected.head())

initial_rows = df_selected.shape[0]
df_selected.drop_duplicates(inplace=True)
final_rows = df_selected.shape[0]

print(f"Initial number of rows: {initial_rows}")
print(f"Number of rows after removing duplicates: {final_rows}")
print(f"Number of duplicate rows removed: {initial_rows - final_rows}")

df_selected['Active'] = df_selected['Active'].apply(lambda x: max(x, 0))

total_confirmed = df_selected['Confirmed'].sum()
total_deaths = df_selected['Deaths'].sum()
total_recovered = df_selected['Recovered'].sum()

print(f"Total Confirmed Cases: {total_confirmed}")
print(f"Total Deaths: {total_deaths}")
print(f"Total Recovered: {total_recovered}")

numerical_columns = ['Confirmed', 'Deaths', 'Recovered', 'Active']
display(df_selected[numerical_columns].describe())

confirmed_cases_over_time = df_selected.groupby('Date')['Confirmed'].sum().reset_index()
display(confirmed_cases_over_time.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.lineplot(x='Date', y='Confirmed', data=confirmed_cases_over_time)
plt.title('Total Confirmed Cases Over Time')
plt.xlabel('Date')
plt.ylabel('Total Confirmed Cases')
plt.grid(True)
plt.show()

confirmed_cases_over_time['Daily New Confirmed'] = confirmed_cases_over_time['Confirmed'].diff().fillna(0)

plt.figure(figsize=(12, 6))
sns.lineplot(x='Date', y='Daily New Confirmed', data=confirmed_cases_over_time)
plt.title('Daily New Confirmed Cases Over Time')
plt.xlabel('Date')
plt.ylabel('Daily New Confirmed Cases')
plt.grid(True)
plt.show()

peak_date = confirmed_cases_over_time.loc[confirmed_cases_over_time['Daily New Confirmed'].idxmax()]
print(f"Peak daily new confirmed cases occurred on {peak_date['Date'].strftime('%Y-%m-%d')} with {int(peak_date['Daily New Confirmed'])} cases.")

confirmed_cases_over_time['Growth Rate'] = confirmed_cases_over_time['Confirmed'].pct_change() * 100

plt.figure(figsize=(12, 6))
sns.lineplot(x='Date', y='Growth Rate', data=confirmed_cases_over_time)
plt.title('Daily Growth Rate of Confirmed Cases Over Time')
plt.xlabel('Date')
plt.ylabel('Growth Rate (%)')
plt.grid(True)
plt.show()

country_cases = df_selected.groupby('Country/Region')[['Confirmed', 'Deaths', 'Recovered']].sum().reset_index()


top_confirmed_countries = country_cases.sort_values(by='Confirmed', ascending=False).head(10)
print('Top 10 Countries by Confirmed Cases:')
display(top_confirmed_countries)


top_deaths_countries = country_cases.sort_values(by='Deaths', ascending=False).head(10)
print('\nTop 10 Countries by Deaths:')
display(top_deaths_countries)


top_recovered_countries = country_cases.sort_values(by='Recovered', ascending=False).head(10)
print('\nTop 10 Countries by Recovered Cases:')
display(top_recovered_countries)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.barplot(x='Confirmed', y='Country/Region', data=top_confirmed_countries, palette='viridis')
plt.title('Top 10 Countries by Confirmed Cases')
plt.xlabel('Total Confirmed Cases')
plt.ylabel('Country/Region')
plt.show()

plt.figure(figsize=(12, 6))
sns.barplot(x='Deaths', y='Country/Region', data=top_deaths_countries, palette='plasma')
plt.title('Top 10 Countries by Deaths')
plt.xlabel('Total Deaths')
plt.ylabel('Country/Region')
plt.show()

plt.figure(figsize=(12, 6))
sns.barplot(x='Recovered', y='Country/Region', data=top_recovered_countries, palette='Greens')
plt.title('Top 10 Countries by Recovered Cases')
plt.xlabel('Total Recovered Cases')
plt.ylabel('Country/Region')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns


correlation_confirmed_deaths = df_selected['Confirmed'].corr(df_selected['Deaths'])
print(f"Correlation between Confirmed and Deaths: {correlation_confirmed_deaths:.2f}")


plt.figure(figsize=(10, 6))
sns.scatterplot(x='Confirmed', y='Deaths', data=df_selected, alpha=0.6)
plt.title('Confirmed Cases vs Deaths')
plt.xlabel('Confirmed Cases')
plt.ylabel('Deaths')
plt.xscale('log')
plt.yscale('log')
plt.grid(True)
plt.show()

correlation_confirmed_recovered = df_selected['Confirmed'].corr(df_selected['Recovered'])
print(f"Correlation between Confirmed and Recovered: {correlation_confirmed_recovered:.2f}")


plt.figure(figsize=(10, 6))
sns.scatterplot(x='Confirmed', y='Recovered', data=df_selected, alpha=0.6)
plt.title('Confirmed Cases vs Recovered Cases')
plt.xlabel('Confirmed Cases')
plt.ylabel('Recovered Cases')
plt.xscale('log')
plt.yscale('log')
plt.grid(True)
plt.show()

correlation_active_confirmed = df_selected['Active'].corr(df_selected['Confirmed'])
print(f"Correlation between Active and Confirmed: {correlation_active_confirmed:.2f}")

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Confirmed', y='Active', data=df_selected, alpha=0.6)
plt.title('Confirmed Cases vs Active Cases')
plt.xlabel('Confirmed Cases')
plt.ylabel('Active Cases')
plt.xscale('log')
plt.yscale('log')
plt.grid(True)
plt.show()